package w32

// WTS CONSTANTS
const (
	WTS_CONSOLE_CONNECT                = 0x1
	WTS_CONSOLE_DISCONNECT             = 0x2
	WTS_REMOTE_CONNECT                 = 0x3
	WTS_REMOTE_DISCONNECT              = 0x4
	WTS_SESSION_LOGON                  = 0x5
	WTS_SESSION_LOGOFF                 = 0x6
	WTS_SESSION_LOCK                   = 0x7
	WTS_SESSION_UNLOCK                 = 0x8
	WTS_SESSION_REMOTE_CONTROL         = 0x9
	WTS_SESSION_CREATE                 = 0xA
	WTS_SESSION_TERMINATE              = 0xB
	WTS_SESSION_CONNECT                = WTS_CONSOLE_CONNECT
	WTS_SESSION_DISCONNECT             = WTS_CONSOLE_DISCONNECT
	WTS_SESSION_LOGON_DEFAULT          = WTS_SESSION_LOGON
	WTS_SESSION_LOGOFF_DEFAULT         = WTS_SESSION_LOGOFF
	WTS_SESSION_REMOTE_CONTROL_DEFAULT = WTS_SESSION_REMOTE_CONTROL
)
